// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_de3QfnJ6GqPoWd9-CgAI9XXpXB1IJ-w',
    appId: '1:281825218279:web:cf4e2b5f945953da5c1c42',
    messagingSenderId: '281825218279',
    projectId: 'eh-vote-usu',
    authDomain: 'eh-vote-usu.firebaseapp.com',
    storageBucket: 'eh-vote-usu.firebasestorage.app',
    measurementId: 'G-ZEP5WSYP65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNiiawfQHczM8SFsWYaU57TfNptXKi-Lc',
    appId: '1:281825218279:android:dcf0caea7503ec595c1c42',
    messagingSenderId: '281825218279',
    projectId: 'eh-vote-usu',
    storageBucket: 'eh-vote-usu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsMODb9v-Oq0OCeJt_rhh7Zs82VN8ix3c',
    appId: '1:281825218279:ios:a2f90fa13caf83565c1c42',
    messagingSenderId: '281825218279',
    projectId: 'eh-vote-usu',
    storageBucket: 'eh-vote-usu.firebasestorage.app',
    iosBundleId: 'com.example.ehVotee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsMODb9v-Oq0OCeJt_rhh7Zs82VN8ix3c',
    appId: '1:281825218279:ios:a2f90fa13caf83565c1c42',
    messagingSenderId: '281825218279',
    projectId: 'eh-vote-usu',
    storageBucket: 'eh-vote-usu.firebasestorage.app',
    iosBundleId: 'com.example.ehVotee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_de3QfnJ6GqPoWd9-CgAI9XXpXB1IJ-w',
    appId: '1:281825218279:web:04452e6ef5289c5d5c1c42',
    messagingSenderId: '281825218279',
    projectId: 'eh-vote-usu',
    authDomain: 'eh-vote-usu.firebaseapp.com',
    storageBucket: 'eh-vote-usu.firebasestorage.app',
    measurementId: 'G-BMF99P0DWT',
  );
}
